import { PrismaD1 } from "@prisma/adapter-d1";
import { PrismaClient } from "@prisma/client";
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error the server build file is generated by `remix vite:build`
import * as build from "../build/server";

// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
export const onRequest = createPagesFunctionHandler<Env>({ build, getLoadContext: ({context}) => {
	const {DB} = context.cloudflare.env;
	const prisma = new PrismaClient({adapter: new PrismaD1(DB)});
	return {prisma, cloudflare: context.cloudflare};
} });
