import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import { getLoadContext } from "../load-context";

// @ts-expect-error the server build file is generated by `remix vite:build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler<Env>({
	build, // eslint-disable-line @typescript-eslint/no-unsafe-assignment
	getLoadContext: getLoadContext,
});
