// Generated by Wrangler on Sun Jun 02 2024 19:26:03 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	session_storage: KVNamespace;
	CF_ENV: string;
	SESSION_COOKIE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DB: D1Database;
}
