// Generated by Wrangler on Fri Jun 07 2024 17:26:58 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	KV_SESSION_STORAGE: KVNamespace;
	CF_ENV: string;
	SESSION_COOKIE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	SUPER_ADMIN_DISCORD_ID: string;
	DB: D1Database;
}
