// Generated by Wrangler on Mon Jun 03 2024 00:11:53 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	KV_SESSION_STORAGE: KVNamespace;
	CF_ENV: string;
	SESSION_COOKIE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DB: D1Database;
}
