#:schema node_modules/wrangler/config-schema.json

name = "project-origin"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-06-02"

[[kv_namespaces]]
binding = "KV_SESSION_STORAGE"
id = "b0b800e360e7459f8f2f74d83ceeb732"

[[d1_databases]]
binding = "DB"
database_name = "dev-project-origin"
database_id = "75ee34c3-dffd-4584-a81f-3f297073a685"

[[env.production.kv_namespaces]]
binding = "KV_SESSION_STORAGE"
id = "e88c92b83db94d7d9c1d7a8fec5108c6"

[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-project-origin"
database_id = "a1f80a18-858e-4be5-adec-57848234f73d"
